from PyQt5 import QtCore, QtGui, QtWidgets
import database
import time
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1098, 668)
        MainWindow.setMinimumSize(QtCore.QSize(1098, 668))
        MainWindow.setMaximumSize(QtCore.QSize(1098, 668))
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.baslik = QtWidgets.QLabel(self.centralwidget)
        self.baslik.setGeometry(QtCore.QRect(290, 10, 551, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.baslik.setFont(font)
        self.baslik.setObjectName("baslik")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 110, 241, 191))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(60, 40, 141, 16))
        self.label.setObjectName("label")
        self.txtAracPlaka_2 = QtWidgets.QTextEdit(self.groupBox)
        self.txtAracPlaka_2.setGeometry(QtCore.QRect(10, 70, 221, 41))
        self.txtAracPlaka_2.setObjectName("txtAracPlaka_2")
        self.aracAra = QtWidgets.QPushButton(self.groupBox)
        self.aracAra.setGeometry(QtCore.QRect(70, 130, 93, 28))
        self.aracAra.setObjectName("aracAra")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(300, 110, 391, 191))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_2)
        self.dateTimeEdit.setGeometry(QtCore.QRect(160, 30, 194, 31))
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 5, 5), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.groupBox_2)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(160, 70, 194, 31))
        self.dateTimeEdit_2.setDate(QtCore.QDate(2021, 5, 5))
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.aracAra1 = QtWidgets.QPushButton(self.groupBox_2)
        self.aracAra1.setGeometry(QtCore.QRect(130, 120, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.aracAra1.setFont(font)
        self.aracAra1.setObjectName("aracAra1")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(273, 120, 20, 511))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(710, 110, 20, 511))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(740, 110, 321, 291))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 141, 41))
        self.label_4.setObjectName("label_4")
        self.txtAracSahibi = QtWidgets.QTextEdit(self.groupBox_3)
        self.txtAracSahibi.setGeometry(QtCore.QRect(130, 50, 181, 41))
        self.txtAracSahibi.setObjectName("txtAracSahibi")
        self.txtAracPlaka = QtWidgets.QTextEdit(self.groupBox_3)
        self.txtAracPlaka.setGeometry(QtCore.QRect(130, 110, 181, 41))
        self.txtAracPlaka.setObjectName("txtAracPlaka")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 141, 41))
        self.label_5.setObjectName("label_5")
        self.txtAracModel = QtWidgets.QTextEdit(self.groupBox_3)
        self.txtAracModel.setGeometry(QtCore.QRect(130, 170, 181, 41))
        self.txtAracModel.setObjectName("txtAracModel")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 170, 141, 41))
        self.label_6.setObjectName("label_6")
        self.aracEkle = QtWidgets.QPushButton(self.groupBox_3)
        self.aracEkle.setGeometry(QtCore.QRect(110, 240, 93, 28))
        self.aracEkle.setObjectName("aracEkle")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(740, 420, 321, 191))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(110, 40, 111, 16))
        self.label_7.setObjectName("label_7")
        self.txtAracSilPlakaAl = QtWidgets.QTextEdit(self.groupBox_4)
        self.txtAracSilPlakaAl.setGeometry(QtCore.QRect(50, 70, 221, 41))
        self.txtAracSilPlakaAl.setObjectName("txtAracSilPlakaAl")
        self.aracSil = QtWidgets.QPushButton(self.groupBox_4)
        self.aracSil.setGeometry(QtCore.QRect(120, 130, 93, 28))
        self.aracSil.setObjectName("aracSil")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 320, 261, 271))
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(300, 320, 391, 271))
        self.listWidget_2.setObjectName("listWidget_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1098, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.aracAra.clicked.connect(self.tekPlakaAracAra)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.aracEkle.clicked.connect(self.aracEkle1)
        self.aracSil.clicked.connect(self.aracSil1)
        self.aracAra1.clicked.connect(self.tarihPlakaAra)

    def tarihPlakaAra(self):
        self.listWidget_2.clear()
        temp_val = self.dateTimeEdit.date()
        var_temp = temp_val.toPyDate()
        temp_val1 = self.dateTimeEdit_2.date()
        var_temp1 = temp_val1.toPyDate()
        a = str(var_temp).split("-")
        year = a[0]
        year = year[2:]
        month = a[1]
        day = a[2]
        decentOne = day + "-" + month + "-" + year
        c = str(var_temp1).split("-")
        year1 = c[0]
        year1 = year1[2:]
        month1 = c[1]
        day1 = c[2]
        decentOne1 = day1 + "-" + month1 + "-" + year1
        kayıtlar = database.zamanaGöreKayıtGetir(decentOne, decentOne1)
        if kayıtlar == -1:
            msg = QMessageBox()
            msg.setWindowTitle("Araç Bulunamadı")
            msg.setText("Aradığınız Zaman Aralığında Herhangi Bir Araç Giriş Yapmamıştır.")
            msg.setIcon(QMessageBox.Warning)
            x = msg.exec_()
        else:
            for kayıt in kayıtlar:
                plaka = database.idyeGöreAracBul(kayıt[0])
                self.listWidget_2.addItem(plaka + "'lı araç " + kayıt[1] + " saatinde giriş yapmıştır.")

    def tekPlakaAracAra(self):

        self.listWidget.clear()
        plaka = self.txtAracPlaka_2.toPlainText()
        plaka = plaka.replace(" ", "")
        plaka = plaka.upper()
        self.txtAracPlaka_2.setText("")
        id = database.plakayaGöreAracBul(plaka)
        if id == -1:
            msg = QMessageBox()
            msg.setWindowTitle("Araç Bulunamadı")
            msg.setText("Aradığınız Araç Veritabanında Bulunmamaktadır...")
            msg.setIcon(QMessageBox.Warning)
            x = msg.exec_()
        else:
            kayıtlar = database.girisKaydıGetirTekArac(id)
            for kayıt in kayıtlar:
                self.listWidget.addItem(kayıt[1] + " " + kayıt[2])

    def aracSil1(self):
        plaka = self.txtAracSilPlakaAl.toPlainText()
        plaka = plaka.replace(" ", "")
        plaka = plaka.upper()
        id = database.plakayaGöreAracBul(plaka)
        if id == -1:
            msg = QMessageBox()
            msg.setWindowTitle("Araç Bulunamadı")
            msg.setText("Aradığınız Araç Veritabanında Bulunmamaktadır...")
            msg.setIcon(QMessageBox.Warning)
            x = msg.exec_()
        else:
            database.aracSil(id)
            msg = QMessageBox()
            msg.setWindowTitle("Araç Silindi")
            msg.setText("Araç Başarı İle Silindi")
            msg.setIcon(QMessageBox.Information)
            x = msg.exec_()
        self.txtAracSilPlakaAl.setText("")

    def aracEkle1(self):
        aracSahibi = self.txtAracSahibi.toPlainText()
        aracPlaka = self.txtAracPlaka.toPlainText()
        aracModel = self.txtAracModel.toPlainText()
        if len(aracSahibi) != 0 and len(aracPlaka) != 0 and len(aracModel) != 0:
            plaka = aracPlaka.replace(" ", "")
            plaka = plaka.upper()
            database.aracEkle(str(aracSahibi), str(plaka), str(aracModel))
            msg = QMessageBox()
            msg.setWindowTitle("Başarılı")
            msg.setText("Başarıyla Veritabanına Eklendiniz")
            msg.setIcon(QMessageBox.Information)
            x = msg.exec_()
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Boş Değer!")
            msg.setText("Değerlerden Birini Boş Girdiniz. Lütfen Tüm Değerleri Giriniz...")
            msg.setIcon(QMessageBox.Warning)
            x = msg.exec_()
        self.txtAracSahibi.setText("")
        self.txtAracModel.setText("")
        self.txtAracPlaka.setText("")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Veritabanı Sorgusu"))
        self.baslik.setText(_translate("MainWindow", "Araç Giriş Kaydı Uygulaması"))
        self.groupBox.setTitle(_translate("MainWindow", "Plakaya Göre Arama"))
        self.label.setText(_translate("MainWindow", "Plaka Giriniz"))
        self.aracAra.setText(_translate("MainWindow", "Ara"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Zamana Göre Arama"))
        self.label_2.setText(_translate("MainWindow", "Başlangıç Tarihi : "))
        self.label_3.setText(_translate("MainWindow", "        Bitiş Tarihi : "))
        self.aracAra1.setText(_translate("MainWindow", "Ara"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Yeni Araç Ekleme"))
        self.label_4.setText(_translate("MainWindow", "Araç Sahibi :"))
        self.label_5.setText(_translate("MainWindow", "Araç Plakası :"))
        self.label_6.setText(_translate("MainWindow", "Araç Modeli : "))
        self.aracEkle.setText(_translate("MainWindow", "Ekle"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Araç Sil"))
        self.label_7.setText(_translate("MainWindow", "Plaka Giriniz"))
        self.aracSil.setText(_translate("MainWindow", "Sil"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
